apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-app-deployment
  namespace: default
  labels:
    app: nova-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nova-app
      tier: frontend
      version: 1.0.0
  template:
    metadata:
      labels:
        app: nova-app
        tier: frontend
        version: 1.0.0
    spec:
      containers:
        - name: nova-app-container
          image: glowbak/nova-app:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nova-app-service
  labels:
    app: nova-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nova-app