apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nova-app
      tier: frontend
      version: 1.0.0
  template:
    metadata:
      labels:
        app: nova-app
        tier: frontend
        version: 1.0.0
    spec:
      containers:
        - name: nova-app-container
          image: 628165586772.dkr.ecr.us-east-1.amazonaws.com/nova-app
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nova-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nova-app