apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nova-app
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: nova-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s